apiVersion: v1
kind: PersistentVolume  #its our physical representation underlying storage pv
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce #at atime only one node can access, multiple pods in that node can also access
  capacity:
    storage: 2Gi
  csi:  #CSI means Container Storage Interface.The EBS CSI driver allows Kubernetes to communicate with AWS EBS.
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle:  vol-028abe5ad18898384
---
apiVersion: v1
kind: PersistentVolumeClaim  #A PVC is a request for storage.PV : "I have 2 GiB of storage available."PVC:"I need 2 GiB of storage
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: #Mount the persistent storage inside the Nginx container at /usr/share/nginx/html
    - name: persistent-storage   
      mountPath: /usr/share/nginx/html
  volumes:  #Now our Pod uses the PVC, not the PV directly.
  - name: persistent-storage 
    persistentVolumeClaim:
      claimName: ebs-static # means Inside this Pod, create a volume called persistent-storage using the PVC ebs-static."
  nodeSelector: #by this selector we can give our node AZ with same match oor (Created volume storage) based on running like ..us-east-1d or us-east-1a...
    topology.kubernetes.io/zone: us-east-1d


##complete picture
#                      AWS
#                   │
#                   ▼
#        EBS Volume: vol-028... we created volume 
#              us-east-1d
#                   │
#                   │ CSI Driver
#                   ▼
#         ┌───────────────────┐
#         │ PersistentVolume  │
#         │    ebs-static     │
#         │      2Gi          │
#         └─────────┬─────────┘
#                   │
#                   │ PVC binds to PV
#                   ▼
#         ┌───────────────────┐
#         │ PersistentVolume  │
#         │      Claim        │
#         │    ebs-static     │
#         │      2Gi          │
#         └─────────┬─────────┘
#                   │
#                   │ claimName
#                   ▼
#               Nginx Pod
#                   │
#                   ▼
#        /usr/share/nginx/html

# And:

# nodeSelector
#      │
#      ▼
# Node must be in us-east-1d
# Easy way to remember

# PV = Kubernetes representation of available storage

# PVC = application asking for storage

# EBS = actual AWS storage

# CSI driver = connects Kubernetes to EBS

# Pod = uses PVC

# nodeSelector = makes sure Pod runs in the correct AZ for this static EBS volume.

# The key difference from your earlier emptyDir example is: emptyDir dies with the Pod, while an EBS-backed PV is persistent and survives Pod deletion/recreation.