apiVersion: v1
kind: pod
metadata:
  name: nginx  #pod name is nginx
  labels:
   project: roboshop
   environment: dev
   purpose: poc
spec: #as i used pod nginx i want to run 
 containers: #its for running of container  nginx
  - name: nginx  #container name
    image: nginx  #for running contianer we need image it will take by docker hub