apiVersion: v1
kind: Pod
metadata:
  name:  multi-container #pod is multi-container name
  labels:
   project: roboshop
   environment: dev
   purpose: poc
spec: #as i used pod nginx i want to run 
 containers: #its for running of container  nginx
  - name: nginx  #container name
    image: nginx  #for running contianer we need image it will take by docker hub
  - name: almalinux
    image: almalinux:9
    command: ["sleep","60"] 