apiVersion: v1
kind: Pod
metadata:
  name: labels #pod name is labels
  labels:
   project: roboshop
   environment: dev
   purpose: poc
spec:
  containers:
    - name: nginx
      image: nginx




      ##################  we can get labels like this in cli

  \* 3.239.39.87 | 172.31.2.126 | t3.micro | https://github.com/srikanth-865/k8-resources.git
[ ec2-user@ip-172-31-2-126 ~/k8-resources ]$ kubectl get pods --show-labels
NAME              READY   STATUS             RESTARTS      AGE     LABELS
labels            1/1     Running            0             2m39s   environment=dev,project=roboshop,purpose=poc
multi-container   1/2     CrashLoopBackOff   4 (49s ago)   7m18s   environment=dev,project=roboshop,purpose=poc
nginx             1/1     Running            0             10m     environment=dev,project=roboshop,purpose=poc  */

