apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
 containers:
   - name: nginx
     image: nginx
     env: #as we are using for nginx container so env values should be inside of the nginx containers 
      - name: project
        value: "roboshop"
      - name: environment
        value: "Dev"
   
   