apiVersion: v1
kind: Pod
metadata:
 name: pod-configuration
spec:
 containers:
  - name: nginx
    image: nginx
    envFrom:  #whatever values we gave in nginx-config here we are using for our nginx container environment values
    - configMapRef:
         name: nginx-config