apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    project: roboshop
    environment: dev
spec:
 selector:
   project: roboshop
   tier: frontend
   component: frontend
 ports:
  - protocol: TCP
    port: 80
    targetport: 80
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx # pod name
#   labels:
#     project: roboshop
#     environment: dev
#     component: frontend
#     tier: frontend
# spec:
#   containers:
#   - name: nginx # container name
#     image: nginx # by default it will get from docker hub