apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    project: roboshop
    environment: dev
spec:
 type: Loadbalancer
 selector:
   project: roboshop
   tier: frontend
   component: frontend
   environment: dev
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007 #we assign our required node value