apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  # replicaset uses these labels to match pods
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
  # pod definition here
  template:
    metadata:
    #matching the replicaset selector labels here pod
      labels:
        project: roboshop
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx

################## OUTPUTS    #########
# NAME             READY   STATUS    RESTARTS   AGE
# frontend-gdb96   1/1     Running   0          2m2s
# frontend-tt82x   1/1     Running   0          2m2s
# frontend-wthj2   1/1     Running   0          2m2s


# frontend (Replicaset Name) - gdb96(Pod name randomly generated)


  