apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels related to deployment resource
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:  #Tells the Deployment controller which Pods to manage (matching the labels).
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
      purpose: deployment
  # Pod defination
  template:  #The blueprint used to create new Pods, defining the container name, image, and ports.
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:2.48.0
        ports:
        - containerPort: 80
---
#service file which is used to for connecting pods and also The Service provides networking to those Pods:
apiVersion: v1
kind: Service
metadata:
  name: nginx
  # servicer labels
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port