apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels related to deployment resource
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:  #Tells the Deployment controller which Pods to manage (matching the labels).
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
      purpose: deployment
  # Pod defination
  template:  #The blueprint used to create new Pods, defining the container name, image, and ports.
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
#service file which is used to for connecting pods and also The Service provides networking to those Pods:
apiVersion: v1
kind: Service
metadata:
  name: nginx
  # servicer labels
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port/target port


#### OUTPUT ######################
# NAME                     READY   STATUS    RESTARTS   AGE
# nginx-596895cffc-88p6b   1/1     Running   0          64s
# nginx-596895cffc-g9mtc   1/1     Running   0          66s
# nginx-596895cffc-q6xxb   1/1     Running   0          65s


# nginx       - 596895cffc       - 88p6b
#   │                │                │
#   │                │                └── Pod-specific ID
#   │                └── ReplicaSet ID
#   └── Deployment name